openapi: 3.0.0
info:
  title: Zoek Kadaster Personen API
  description: |
    API voor het zoeken van Kadaster Natuurlijk Personen met free query op geslachtsnaam (minimaal 2 karakters, exact match) en geboortedatum (optioneel, format: dd-MM-yyyy)  
    of  
    zoeken van Kadaster- of Ingeschreven Niet Natuurlijk Personen met free query op statutaire naam (minimaal 2 karakters, exact match) en statutaire zetel (optioneel)
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
  version: 1.0.0
paths:
  /kadasterpersonen:
    get:
      operationId: GetKadasterpersonen
      description: "Zoeken naar Kadaster personen op basis van free query.  
        Resultaat wordt gesorteerd op geslachtsnaam/statutairenaam, voorvoegsel, voornamen, geboortedatum"
      parameters: 
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: |
            free query op geslachtsnaam (minimaal 2 karakters, exact match) en geboortedatum (optioneel, format: dd-MM-yyyy)  
            of  
            free query op statutaire naam (minimaal 2 karakters, exact match) en statutaire zetel (optioneel)
        - name: rechtsvormcode
          in: query
          required: false
          schema:
            type: string
          description: |
            code van een rechtsvorm, bepaald uit de rechtsvorm waardelijst
        - name: zoektype
          in: query
          required: false
          schema:
            type: string
            enum:
            - np
            - nnp
          description: |
            np: zoeken naar KadasterNatuurlijkPersonen  
            nnp: zoeken naar KadasterNietNatuurlijkPersonen en IngeschrevenNietNatuurlijkPersonen

            Als er geen type wordt opgegeven, wordt er naar zowel KadasterNatuurlijkPersonen, KadasterNietNatuurlijkPersonen en IngeschrevenNietNatuurlijkPersonen gezocht
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/warning"
            X-Rate-Limit-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/X_Rate_Limit_Limit"
            X-Rate-Limit-Remaining:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/X_Rate_Limit_Remaining"
            X-Rate-Limit-Reset:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/X_Rate_Limit_Reset"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/KadasterPersoonHalCollectie'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/403"
        '404':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/404"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/500"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/503"
      tags:
        - kadasterpersonen
components:
  schemas:
    KadasterPersoonHalCollectie:
      type: object
      properties:
        _link:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalCollectionLinks"
        kadasterPersonen:
          type: array
          items:
            $ref: '#/components/schemas/KadasterPersoonHal'
    KadasterPersoonHal:
      description: |
        abstract base class voor Kadaster personen met HAL links t.b.v. toepassen van polymorphisme.
      allOf:
        - $ref: '#/components/schemas/KadasterPersoon'
      properties:
        _link:
          $ref: '#/components/schemas/KadasterPersoon_links'
      discriminator:
        propertyName: kadasterPersoonType
    KadasterPersoon_links:
      type: object
      properties:
        self:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalLink"
    KadasterNatuurlijkPersoonHal:
      allOf:
        - $ref: '#/components/schemas/KadasterNatuurlijkPersoon'
        - $ref: '#/components/schemas/KadasterPersoon_links'
    KadasterNietNatuurlijkPersoonHal:
      allOf:
        - $ref: '#/components/schemas/KadasterNietNatuurlijkPersoon'
        - $ref: '#/components/schemas/KadasterPersoon_links'
    IngeschrevenNietNatuurlijkPersoonHal:
      allOf:
        - $ref: '#/components/schemas/IngeschrevenNietNatuurlijkPersoon'
        - $ref: '#/components/schemas/KadasterPersoon_links'
    KadasterPersoon:
      oneOf:
#       - $ref: '#/components/schemas/AbstractKadasterPersoon'
        - $ref: '#/components/schemas/KadasterNatuurlijkPersoonHal'
        - $ref: '#/components/schemas/KadasterNietNatuurlijkPersoonHal'
        - $ref: '#/components/schemas/IngeschrevenNietNatuurlijkPersoonHal'
      discriminator:
        propertyName: kadasterPersoonType
    AbstractKadasterPersoon:
      type: object
      description: |
        abstract base class voor Kadaster personen t.b.v. toepassen van polymorphisme.
      properties:
        identificatie:
          type: string
    KadasterNatuurlijkPersoon:
      allOf:
        - $ref: '#/components/schemas/AbstractKadasterPersoon'
      properties:
        voornamen:
          type: string
        voorvoegselGeslachtsnaam:
          type: string
        geslachtsnaam:
          type: string
        geboorte:
          $ref: '#/components/schemas/Geboorte'
    IngeschrevenNietNatuurlijkPersoon:
      allOf:
        - $ref: '#/components/schemas/KadasterNietNatuurlijkPersoon'
      properties:
        kvknummer:
          type: string
        rsin:
          type: string
    KadasterNietNatuurlijkPersoon:
      allOf:
        - $ref: '#/components/schemas/AbstractKadasterPersoon'
      properties:
        statutaireNaam:
          type: string
        vestiging:
          type: string
    Geboorte:
      description: |
        Gegevens over de geboorte van respectievelijk de persoon, de ouder,
        de echtgenoot/geregistreerd partner, de eerdere echtgenoot/geregistreerd
        partner of het kind.
        * **datum** : Datum waarop de persoon is geboren.
        * **land** : Land waar de persoon is geboren.
        * **plaats** : De plaats waar een persoon is geboren. Voor een plaats buiten Nederland is gemeentecode=1999
        (RNI) en gemeentenaam de buitenlandse plaatsnaam of aanduiding.
      type: object
      properties:
        datum:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Datum_onvolledig"
        land:
          $ref: '#/components/schemas/Waardelijst'
        plaats:
          $ref: '#/components/schemas/Waardelijst'
    Waardelijst:
      type: object
      description:
        Generieke tabel met waarden om een code en omschrijving op te nemen.
      properties:
        code:
          type: string
          title: code
          description: ""
        omschrijving:
          type: string
          title: omschrijving
          description: ""
