openapi: 3.0.0
info:
  title: Kadaster - BRK-Bevragen API - Beslagen endpoints
  description: "De definitie van de Beslagen endpoints en components"
  version: "1.1.0"
paths:
  /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/beslagen:
    get:
      operationId: GetBeslagenKadastraalOnroerendeZaak
      description: |
        Het raadplegen van beslagen en beslagleggers van een kadastraal onroerende zaak.

        Met gebruik van de parameter expand kunnen gerelateerde stukken en stukdelen direct worden meegeladen.
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/fields"
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/expand"
        - in: path
          name: kadastraalonroerendezaakidentificatie
          description: "De unieke identificatie van een kadastraal onroerende zaak."
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/warning"
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/BeslagHalCollectie"
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/403"
        '404':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/404"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/406"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/410"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/500"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/503"
      tags:
      - Beslagen
  /beslagen/{beslagidentificatie}:
    get:
      operationId: GetBeslag
      description: |
        Het raadplegen van een beslag.

        Met gebruik van de parameter expand kunnen gerelateerde stukken en stukdelen direct worden meegeladen.
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/fields"
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/expand"
        - in: path
          name: beslagidentificatie
          description: "De unieke identificatie van het beslag."
          required: true
          schema:
            type: string
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/acceptCrs"
      responses:
        '200':
          description: "Raadplegen geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/warning"
            Content-Crs:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/contentCrs"
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/BeslagHal"
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/403"
        '404':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/404"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/406"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/410"
        '412':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/412"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/415"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/500"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/503"
      tags:
      - Beslagen
  /beslagen:
    get:
      operationId: GetBeslagen
      description: |
        Het zoeken van beslagen die door een specifieke beslaglegger zijn gelegd. De beslaglegger kan een ingeschreven persoon zijn (gebruik beslaglegger__burgerservicenummer) of een kadasterpersoon (gebruik beslaglegger__identificatie).

        Met gebruik van de parameter expand kunnen gerelateerde stukken en stukdelen direct worden meegeladen.
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/fields"
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/expand"
        - in: query
          name: beslaglegger__burgerservicenummer
          description: "Het burgerservicenummer van de ingeschreven persoon."
          required: false
          schema:
            type: string
            maxLength: 9
        - in: query
          name: beslaglegger__identificatie
          description: "De kadastrale identificatie van een persoon of een rechtspersoon die bij het kadaster geregistreerd is."
          required: false
          schema:
            type: string
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/page"
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/pageSize"
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/warning"
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/BeslagHalPagedCollectie"
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/403"
        '404':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/404"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/406"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/410"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/500"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/503"
      tags:
      - Beslagen
components:
  schemas:
    Beslag:
      type: "object"
      description: |
        Tijdelijke maatregel opgelegd door een partij waardoor de zakelijk gerechtigde niets met de kadastraal onroerende zaak kan doen.

        Waardelijst in deze component :
        - [omschrijvingBetrokkenRecht](http://www.kadaster.nl/schemas/waardelijsten/BetrokkenRecht/) en [aard](http://www.kadaster.nl/schemas/waardelijsten/AardBeslag/)
      properties:
        identificatie:
          type: "string"
        domein:
          type: "string"
          description: "Het domein waartoe de identificatie behoort."
        aandeelInBetrokkenRecht:
          $ref: "domain.yaml#/components/schemas/TypeBreuk"
        gedeeltelijkeBezwaringOudObject:
          type: "boolean"
          description: "Indicatie of het object waarop beslag is gelegd gedeeltelijk uit een inmiddels vervallen object bestaat."
        omschrijvingBetrokkenRecht:
          $ref: "domain.yaml#/components/schemas/Waardelijst"
          description: "Mogelijke waarden zijn te vinden in deze [Waardelijst](http://www.kadaster.nl/schemas/waardelijsten/BetrokkenRecht/)"
        toelichtingBewaarder:
          type: "string"
          description: "Toelichtende tekst van de bewaarder. De bewaarder is iemand die bij het Kadaster werkt. Hij schrijft stukken in in de openbare registers en de basisregistratie Kadaster conform de Kadasterwet."
        aard:
          $ref: "domain.yaml#/components/schemas/Waardelijst"
          description: "Mogelijke waarden zijn te vinden in deze [Waardelijst](http://www.kadaster.nl/schemas/waardelijsten/AardBeslag/)"
        aantekeningen:
          type: array
          items:
            $ref: "domain.yaml#/components/schemas/Aantekening"
            description: "Een aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een beslag is theoretisch mogelijk, maar komt bijna niet voor."
        beslagleggers:
          type: array
          items:
            $ref: "domain.yaml#/components/schemas/PersoonBeperkt"
            description: "Partij die beslag legt op een kadastraal onroerende zaak, waardoor de zakelijk gerechtigde niets met de kadastraal onroerende zaak kan doen."
        stukIdentificaties:
          type: "array"
          description: "Dit element is de identificatie van het Stuk. Dit kan een aangeboden Stuk of een Kadasterstuk zijn."
          items:
            type: string
        isGebaseerdOpStukdeelIdentificatie:
          type: "string"
          description: "De identificatie van het stukdeel (paragraaf in een akte met een rechtsfeit) waarop dit beslag is gebaseerd."
        isVermeldInStukdeelIdentificaties:
          type: "array"
          description: "De identificaties van de stukdelen (paragrafen in een akte met een rechtsfeit) waarin dit beslag is vermeld"
          items:
            type: "string"
        onroerendeZaakIdentificatie:
          type: "string"
          description: "identificatie van de Kadastraal onroerende zaak waar het beslag op rust"
    BeslagHal:
      allOf:
      - $ref: "#/components/schemas/Beslag"
      - properties:
          _links:
            $ref: "#/components/schemas/Beslag_links"
          _embedded:
            $ref: "#/components/schemas/Beslag_embedded"
    BeslagHalCollectie:
      type: "object"
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalCollectionLinks"
        _embedded:
          type: "object"
          properties:
            beslagen:
              type: "array"
              items:
                $ref: "#/components/schemas/BeslagHal"
    BeslagHalPagedCollectie:
      type: "object"
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalPaginationLinks"
        _embedded:
          type: "object"
          properties:
            beslagen:
              type: "array"
              items:
                $ref: "#/components/schemas/BeslagHal"
    Beslag_embedded:
      properties:
        stukken:
          $ref: "stukken.yaml#/components/schemas/StukHalBasis"
        isGebaseerdOpStukdeel:
          $ref: "stukken.yaml#/components/schemas/StukdeelHal"
        isVermeldInStukdelen:
          type: "array"
          items:
            $ref: "stukken.yaml#/components/schemas/StukdeelHal"
    Beslag_links:
      type: "object"
      properties:
        beslagleggers:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        stukken:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        isGebaseerdOpStukdeel:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        isVermeldInStukdelen:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        betrokkenPersonen:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        rustOpObject:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
    