name: publish 'in productie' user stories

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          echo -e '---\nlayout: page-with-side-nav\ntitle: User Stories in Productie\n---\n' >> issues.md
          echo -e '# User stories\n' >> issues.md
          
      - name: List 'BRK bevragen v1.2.1' user stories
        uses: lee-dohm/select-matching-issues@v1.2.0
        with:
          format: list
          query:  'label:BRK bevragen v1.2.1 label:User Story'
          token: ${{ secrets.USER_TOKEN }}
          path: issues-tmp.md
          
      - run: |
          cat issues-tmp.md >> issues.md
          echo -e '\n' >> issues.md
        
      - name: List 'BRK bevragen v1.2' user stories
        uses: lee-dohm/select-matching-issues@v1.2.0
        with:
          format: list
          query:  'label:BRK bevragen v1.2 label:User Story'
          token: ${{ secrets.USER_TOKEN }}
          path: issues-tmp.md

      - run: |
          cat issues-tmp.md >> issues.md
          echo -e '\n' >> issues.md
      - run: |
          sed -i 's/)/){:target="_blank" rel="noopener"}/' issues.md
          mv issues.md ./docs/user-stories-prod.md

          if [ -n "$(git status ./docs/user-stories-prod.md --porcelain)" ]; then
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add ./docs/user-stories-prod.md
            git commit -m "commit generated user stories in productie artifacts"
            git push
          fi
          
